on:
  push:
    branches:
      - master 




jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'testing githu action'
        run: pwd
      - name: 'testing printing'
        run: echo ahmed
